export const samplePostingsData = [
  {
    role: "Full-Stack Developer",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Team Hub",
    description:
      "Are you a Web/Full-Stack Developer looking to get involved in a cool project? Come check out Team Hub, a web application we are building to make member tracking and onboarding easy for Waterloop. You will gain valuable experience with frontend and backend web technologies, doing anything from Web API development to responsive webpage design. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Web API development and testing using Node JS and MongoDB",
      "Front-end webpage development using React JS, Styled Components and Styled System",
    ],
    requirements: [
      "Recommended: Prior experience with React JS",
      "Recommended: Prior experience with CSS",
      "Recommended: Prior experience with Node JS",
      "Recommended: Prior experience with MongoDB",
    ],
    additional: ["5 hr/week time commitment"],
  },
  {
    role: "Front-End Developer",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Team Hub",
    description:
      "Are you a Web/Full-Stack Developer looking to get involved in a cool project? Come check out Team Hub, a web application we are building to make member tracking and onboarding easy for Waterloop. You will gain valuable experience with frontend technologies like React JS, Javascript, and CSS. Design responsive webpages and create amazing user experiences using wireframing tools like Adobe XD. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Developing cool webpage features using the latest front-end technologies like React JS, Styled Components and Styled System",
      "Wireframing and UI/webpage design using Adobe XD and Figma",
    ],
    requirements: [
      "Recommended: Prior experience with React JS",
      "Recommended: Prior experience with Redux",
      "Recommended: Prior experience with UI/UX Design",
      "Recommended: Prior experience with CSS",
      "Recommended: Prior experience with Styled Components",
      "Recommended: Prior experience with Styled Systems",
    ],
    additional: ["5 hr/week time commitment"],
  },
  {
    role: "Graphic Designer",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Business",
    description:
      "The business team is responsible for the marketing, sponsorship, and finance side of things at Waterloop. From posting social media campaigns to filling out funding applications and communicating with sponsors, the business team works hard to promote the Waterloop brand and support it financially. The team works to increase the adoption of hyperloop technology as the future of transportation. The graphics team helps create a cohesive public presence for the team. Graphics team members establishes the Waterloop brand, and ensures we are represented professionally. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Design social media posts (Twitter, Instagram, Facebook, LinkedIn)",
      "Designing and coordinating team merch",
      "Refining the team sponsorship package",
      "Helping establish the Waterloop brand",
    ],
    requirements: [
      "Experience with Adobe XD, Illustrator, InVision, Figma or equivalent",
      "Recommended: Prior graphic design experience",
    ],
    additional: ["6 hr/week time commitment"],
  },
  {
    role: "Photographer/ Videographer",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Business",
    description:
      "The business team is responsible for the marketing, sponsorship, and finance side of things at Waterloop. From posting social media campaigns to filling out funding applications and communicating with sponsors, the business team works hard to promote the Waterloop brand and support it financially. The team works to increase the adoption of hyperloop technology as the future of transportation. We are looking for someone to function as a team photographer and videographer. Preference will be given to individuals who will be available to take photos and videos in-person. Additionally looking for someone interested in helping Waterloo create video content and launch a team YouTube channel. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Create video and photo content for our social medias, sponsorship packages and website",
      "Video and photo editing",
      "Storyboard creation and planning videos to promote the team",
      "Launching Waterloop's YouTube channel",
    ],
    requirements: [
      "Experience with Final Cut Pro or equivalent",
      "Experience with Adobe Lightroom or equivalent",
      "Recommended: Prior experience with content creation for teams/clubs",
      "Recommended: Will be living in Waterloo for the Fall term/willing to come to Waterloop to take photos and videos in our bay",
    ],
    additional: [
      "Estimated 6 hr/week time commitment",
      "Flexible schedule to meet members during testing/work sessions",
    ],
  },
  {
    role: "Infrastructure Team Member",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Infrastructure",
    description:
      "The Waterloop Infrastructure team was founded with the purpose of building a functional Hyperloop test track right on UW campus. The infra team is currently submitting a formal proposal to UW admins, and in the coming term will have to prepare a track design, seek out sponsors, plan events, interface with UW, perform cost analysis, and find contractors. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Track design and manufacturing",
      "Researching and applying to grants",
      "Reaching out to sponsors, and contractors",
      "Budgeting",
      "Event planning",
      "Project management",
    ],
    requirements: [
      "To be learned: Civil/transportation engineering",
      "To be learned: Project management",
      "To be learned: Event planning",
      "To be learned: Mechanical design",
      "To be learned: Industry networking",
    ],
    additional: ["5 hr/week time commitment"],
  },
  {
    role: "Braking Team Member",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Mechnical",
    description:
      "The mechanical team is in charge of the design, fabrication, and testing of all physical mechanisms for structures, guidance, and propulsion subsystems on the Hyperloop pod. The team uses skills in CAD, drafting, as well as analysis through simulations. The braking team is responsible for the pod's braking system. This includes mechanical design, pneumatic circuit design, fabrication and physical assembly of the system. Kinematic calculations and experimental validation are also a part of the role. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Mechanical design for structural brackets",
      "Design of pneumatic circuits and structural Finite Element Analysis",
      "Use of machine shop equipment: lathe, mill, bandsaw, drill-press, etc",
    ],
    requirements: [
      "Basic CAD skills",
      "To be learned: FEA",
      "To be learned: Machine Shop skills",
      "To be learned: Mechnical design experience",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Composites Manufacturing Team Member",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Mechanical",
    description:
      "The mechanical team is in charge of the design, fabrication, and testing of all physical mechanisms for structures, guidance, and propulsion subsystems on the Hyperloop pod. The team uses skills in CAD, drafting, as well as analysis through simulations. Composites manufacturing team members will work on manufacturing various parts for the Mechanical subteam out of composite materials. These are usually structural members or aerodynamic bodywork parts. This project requires lots of hands-on carbon fibre manufacturing, technical documentation and CAD design. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "CAD design",
      "Machining with wood and aluminum",
      "Mold design",
      "Carbon fibre layup",
      "Manufacturing an aerodynamic carbon fibre shell for our latest Goose 5 pod",
    ],
    requirements: [
      "Must be living in Waterloo in the Fall term, or willing to come to Waterloo to participate in in-person work",
      "To be learned: Design for composite materials",
      "To be learned: Manufacturing process of composite materials",
      "To be learned: Basic aerodynamics",
      "To be learned: FEA",
      "To be learned: Use of Machine Shop tools",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Mechanical Designer",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Mechanical",
    description:
      "The mechanical team is in charge of the design, fabrication, and testing of all physical mechanisms for structures, guidance, and propulsion subsystems on the Hyperloop pod. The team uses skills in CAD, drafting, as well as analysis through simulations. The mechanical subteam is looking for a new recruit to work in tandem with the electrical team to design electronics panels and enclosures for our Goose 5 pod's power electronics. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Designing electrical enclosures and panels with the electrical team",
      "Wiring diagrams",
      "General electronics packaging",
      "Designing mounting solutions for sensors",
    ],
    requirements: [
      "Basic CAD skills",
      "To be learned: FEA",
      "To be learned: Machine Shop skills",
      "To be learned: Mechnical design experience",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Mech Co-op",
    deadline: "Rolling basis, see WaterlooWorks",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Mechanical",
    description:
      "Co-op position for the mech subteam. Will work on various projects that involve mechanical CAD design, FEA, technical documentation, machining. All these projects will work towards making our latest pod: Goose 5 functional by S21.",
    tasks: [
      "Projects may vary depending on the student's interest and skills. Preferably, the focus will lie in manufacturing/assembly of pod sytems. Some options include manufacturing and assembly of remaining pod components, carbon fiber shell manufacturing, and LIM testing.",
    ],
    requirements: [
      "Basic CAD skills",
      "Report writing experience",
      "Living in Waterloo for the Fall term and willing to do in-person work at our bay",
      "Recommended: Prior experience with FEA",
      "Recommended: Prior experience with machine shop skills",
      "Recommended: Design experience",
    ],
    additional: [
      "This position is mainly in-person but also involves some remote work. This position will count towards your co-op credit",
      "Full time position",
    ],
  },
  {
    role: "E&M / CAE Analyst",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "LIM",
    description:
      "The Linear Induction Motor (LIM) is the propulsion system for the pod. It is similar in principle to a rotary induction motor, but makes use of a different geometry. The LIM team is responsible for the design, manufacturing, and testing of LIMs. Waterloop has been iteratively improving our LIMs, but much of the optimization remains to be done. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "The E&M/CAE analysis team will be responsible for researching various factors of the LIM, and developing simulations. The team will be preparing designs for the motor development team to prototype and test to verify simulation results.",
    ],
    requirements: [
      "A deep interest in E&M and motor design",
      "Basic CAD skills",
      "At least 1 year commitment to the team",
      "Willingness to read textbooks in spare time",
      "Prior knowledge in induction motors",
      "Recommended: having taken any relevant courses such as ME269, MTE120, etc.",
      "To be learned: Motor design",
      "To be learned: FEA and simulations",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Motor Development / Test Stand Engineering",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "LIM",
    description:
      "The Linear Induction Motor (LIM) is the propulsion system for the pod. It is similar in principle to a rotary induction motor, but makes use of a different geometry. The LIM team is responsible for the design, manufacturing, and testing of LIMs. Waterloop has been iteratively improving our LIMs, but much of the optimization remains to be done. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "The motor development team will be responsible for manufacturing various prototype LIMs to test and verify simulation results. ",
    ],
    requirements: [
      "A deep interest in E&M and motor design",
      "At least 1 year commitment to the team",
      "Willingness to read textbooks in spare time",
      "Living in Waterloo over the Fall term and willing to participate in in-person work",
      "Recommended: prior knowledge and/or experience with electric motors",
      "Recommended: having taken any relevant courses such as ME269, MTE120, etc.",
      "Recommended: Basic embedded programming",
      "To be learned: Motor design",
      "To be learned: FEA and simulations",
      "To be learned: Rapid Prototyping",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Embedded",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Electrical",
    description:
      "The electrical team works on powering and controlling the Hyperloop pod while providing sensor feedback. The team has a strong focus on both HV and LV development in battery management, motor control and embedded sensing. The embedded electrical team is developing a comprehensive sensor system to ensure accurate measurements can be taken from our pod. These sensors may measure temperature, pressure, current, optical, voltage and more. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Design, build and test sensor boards",
      "Develop low-level firmware for sensors (depending on your interest) ",
      "Assemble and test sensor boards in-person",
    ],
    requirements: [
      "Experience creating and conducting test plans (verifying sensors, power output, etc)",
      "Recommended: Living in Waterloo or willing to come to Waterloo to participate in in-person work",
      "To be learned: Circuit design (sensors, analog design, MCUs)",
      "To be learned: FEA and simulations",
      "To be learned: Schematic capture and PCB layout (Altium preferred, KiCAD also welcome)",
      "To be learned: Electrical assembly skills (SMT solder and reflow preferred)",
      "To be learned: Electrical measurement tools (multimeter, oscilloscope)",
      "To be learned: Embedded development (STM32, Arduino preferred)",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Motor Control",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Electrical",
    description:
      "The electrical team works on powering and controlling the Hyperloop pod while providing sensor feedback. The team has a strong focus on both HV and LV development in battery management, motor control and embedded sensing. \nWaterloop is developing a controller for our propulsion system. Controls are primarily implemented in software, however the control algorithm will be verified in PSIM. Hardware is being designed to drive high power switches and provide sensor feedback.",
    tasks: [
      "Design, build and test sensor boards",
      "Develop low-level firmware for sensors (depending on your interest) ",
      "Assemble and test sensor boards in-person",
    ],
    requirements: [
      "Know/be willing to learn ECE463/ECE420",
      "Recommended: Prior experience with power electronics",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Battery Management System (BMS)",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Electrical",
    description:
      "The electrical team works on powering and controlling the Hyperloop pod while providing sensor feedback. The team has a strong focus on both HV and LV development in battery management, motor control and embedded sensing. The battery management system team is developing an in-house BMS to monitor properties of individual cells, and provide cell balancing where needed. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Design, build and test sensor boards that measure battery cells to ensure optimal conditions/that measure power to components such as the motor controller",
      "Assemble and test sensor boards in-person",
    ],
    requirements: [
      "To be learned: Circuit design (MCUs, power electronics)",
      "To be learned: Schematic capture and PCB layout (Altium preferred, KiCAD also welcome)",
      "To be learned: Electrical assembly skills (SMT solder and reflow experience)",
      "To be learned: Electrical measurement tools (multimeter, oscilloscope)",
      "To be learned: Experience creating and conducting test plans (verifying sensors, power output, etc)",
      "Recommended: Living in Waterloo or willing to come to Waterloo to participate in in-person work",
    ],
    additional: ["10 hr/week time commitment"],
  },
  {
    role: "Electrical Co-op",
    deadline: "Rolling basis, see WaterlooWorks",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Electrical",
    description:
      "The electrical team works on powering and controlling the Hyperloop pod while providing sensor feedback. The team has a strong focus on both HV and LV development in battery management, motor control and embedded sensing. As the electrical co-op, you will be working on developing and testing our embedded sensors and in-house battery management system. This position is mainly in-person, but also involves some remote work. This position will count towards your co-op credit.",
    tasks: [
      "Design, build and test sensor boards; including LV sensor boards for embedded systems and HV power distribution boards for our BMS",
      "Working closely with the software team to provide electrical support and assist in testing where necessary",
    ],
    requirements: [
      "Living in Waterloo for the Fall term and willing to do in-person work at our bay",
      "Recommended: Circuit design (sensors, MCUs, power electronics are all applicable)",
      "Recommended: Schematic capture and PCB layout (Altium preferred, KiCAD also welcome)",
      "Recommended: Electrical assembly skills (SMT solder and reflow experience)",
      "Recommended: Electrical measurement tools (multimeter, oscilloscope)",
      "Recommended: Experience creating and conducting test plans (verifying sensors, power output, etc)",
    ],
    additional: [
      "This position is mainly in-person but also involves some remote work. This position will count towards your co-op credit",
      "Full time position",
    ],
  },
  {
    role: "Software Developer - Embedded",
    deadline: "September 17, 2020 (rolling basis)",
    term: "FALL 2020",
    applicationForm: "https://forms.gle/8uq54fDQohq33D166",
    subteam: "Software",
    description:
      "The software team works on all software components related to the pod. We are responsible for developing and testing all the sensors, embedded boards, and testing rigs. Currently the team is working on the motor controller, battery management system (BMS), coding new sensor boards, remote flashing rig and testing rig. Waterloop will be accepting members on a rolling basis.",
    tasks: [
      "Working with low-level languages (C/C++) to code embedded boards",
      "Create and work through different tests for sensors",
    ],
    requirements: [
      "A solid foundation in C/C++",
      "Understanding of common communication protocols (I2C, SPI, USB)",
      "Experience working with Arduino",
      "Recommended: Prior experience with STM32 boards",
      "Recommended: Living in Waterloo",
    ],
    additional: ["10 hr/week time commitment"],
  },
];
