export const POSTINGS_SET_POSTINGS = 'POSTINGS_SET_POSTINGS';
export const POSTINGS_SET_POSTING_BY_ID = 'POSTINGS_SET_POSTING_BY_ID';

export const TEAMS_SET_TEAMS = 'TEAMS_SET_TEAMS';

export const SPONSORS_SET_SPONSORS = 'SPONSORS_SET_SPONSORS';
export const SPONSORS_SET_SPONSOR_DESC = 'SPONSORS_SET_SPONSOR_DESC';
export const SPONSORS_SET_SPONSOR_TIERS = 'SPONSORS_SET_SPONSOR_TIERS';
